---
name: "FishingRod"
description: "Fishing Rod for PvP, plugin for Pocketmine-MP."
src-namespace-prefix: MXJosueDev\fishingrod
version: "2.0.1"
main: MXJosueDev\fishingrod\Loader
api: "5.0.0"
author: "MXJosueDev"
website: "https://github.com/MXJosueDev/FishingRod"
...