---
name: FishingRod
description: Fishing Rod for PvP, plugin for Pocketmine-MP.
src-namespace-prefix: fishingrod
version: 0.1-Beta
main: fishingrod\Loader
api: "4.2.x"
author: MXJosueDev
website: https://github.com/MXJosueDev/FishingRod
...